version: "3.8"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    environment: []

    volumes:
      - ..:/workspaces:cached

    command: sleep infinity

  broker:
    hostname: wabbit
    image: rabbitmq:3.12.8

    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
